import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Deploy the built runtime files into the live Obsidian vault so they sync with
// the notes (single-repo workflow). Override with OBSIDIAN_PLUGIN_DIR if the
// vault lives elsewhere. Set to an empty string to skip deployment.
const deployDir =
	process.env.OBSIDIAN_PLUGIN_DIR ??
	path.resolve(
		'../../Documents/Notes/.obsidian/plugins/obsidian_freeflow_text_plugin',
	);

const deployPlugin = {
	name: 'deploy-to-vault',
	setup(build) {
		build.onEnd((result) => {
			if (!deployDir || result.errors.length) return;
			try {
				fs.mkdirSync(deployDir, { recursive: true });
				for (const file of ['main.js', 'manifest.json', 'styles.css']) {
					if (fs.existsSync(file)) {
						fs.copyFileSync(file, path.join(deployDir, file));
					}
				}
				console.info(`[deploy] copied runtime files to ${deployDir}`);
			} catch (err) {
				console.error(`[deploy] failed: ${err.message}`);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [deployPlugin],
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
