import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Deploy the built runtime files into the live Obsidian vaults so they sync with
// the notes. The vaults are the Remotely Save copies in the user's personal
// OneDrive; the OneDrive client uploads the copied files automatically and
// Remotely Save pulls them onto each device. Override with OBSIDIAN_PLUGIN_DIR
// (a single path, or several separated by commas) if the vaults live elsewhere.
// Set it to an empty string to skip deployment.
const pluginSubpath = '.obsidian/plugins/obsidian_freeflow_text_plugin';
const oneDriveVaultRoot = path.join(
	os.homedir(),
	'Library/CloudStorage/OneDrive-Personal/Apps/remotely-save',
);
// Only Notes is actively maintained (Work and Theology were merged into it), but a default
// vault that doesn't exist yet is skipped rather than created either way, so a build never
// plants a phantom vault folder in OneDrive.
const defaultVaultDirs = ['Notes'].map((name) => path.join(oneDriveVaultRoot, name));

const deployTargets =
	process.env.OBSIDIAN_PLUGIN_DIR !== undefined
		? process.env.OBSIDIAN_PLUGIN_DIR.split(',')
				.map((dir) => dir.trim())
				.filter((dir) => dir.length > 0)
				.map((dir) => ({ deployDir: dir, vaultDir: null }))
		: defaultVaultDirs.map((vaultDir) => ({
				deployDir: path.join(vaultDir, pluginSubpath),
				vaultDir,
			}));

const deployPlugin = {
	name: 'deploy-to-vault',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length) return;
			for (const { deployDir, vaultDir } of deployTargets) {
				try {
					if (vaultDir !== null && !fs.existsSync(vaultDir)) {
						console.info(`[deploy] skipped ${vaultDir} (vault not found)`);
						continue;
					}
					fs.mkdirSync(deployDir, { recursive: true });
					for (const file of ['main.js', 'manifest.json', 'styles.css']) {
						if (fs.existsSync(file)) {
							fs.copyFileSync(file, path.join(deployDir, file));
						}
					}
					console.info(`[deploy] copied runtime files to ${deployDir}`);
				} catch (err) {
					console.error(`[deploy] failed for ${deployDir}: ${err.message}`);
				}
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [deployPlugin],
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
